#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Nov  9 13:12:01 2021

@author: ryanpennell
"""

class Coordinate(object):
    def __init__(self, x, y):
        self.x = x
        self.y = y
    def distance(self, other):
        x_diff_sq = (self.x-other.x)**2
        y_diff_sq = (self.y-other.y)**2
        return (x_diff_sq + y_diff_sq)**0.5
    def __str__(self):
        return "<" + str(self.x) + "," + str(self.y) + ">"
    def __sub__(self, other):
        return Coordinate(self.x - other.x, self.y - other.y)
    def add(self, other):
        x_add_ = (self.x+other.x)
        y_add_ = (self.y+other.y)
        return Coordinate(x_add_, y_add_)
    def sub(self, other):
        x_sub_ = (self.x-other.x)
        y_sub_ = (self.y-other.y)
        return Coordinate(x_sub_, y_sub_)
        
origin = Coordinate(0,0)
